version: '3'
services:
  mongo:
    container_name: mongo-container
    image: mongo:4
    logging:
      driver: none
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
